version: "3"

services:
  database-reward:
    image: postgres:alpine
    restart: always
    expose:
      - 7032
    ports:
      - "7032:5432"
    volumes:
      - rewarddata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=reward_service
  app-reward:
    build:
      context: ./../reward_service # necessary because otherwise docker-compose overrides the context path when merging multiple docker-compose.yml files
      dockerfile: Dockerfile
    restart: always
    container_name: reward_service
    expose:
      - 7000
      - 7001
    ports:
      - "7000:7000"
      - "7001:7001"
    depends_on:
      - database-reward
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database-reward:5432/reward_service
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
  dapr-reward:
    image: "daprio/daprd"
    command: [
      "./daprd",
      "--app-id", "reward_service",
      "--app-port", "7001",
      "--dapr-http-port", "7000",
      "--resources-path", "./components"
    ]
    volumes:
      - "./../reward_service/components/:/components" # Mount our components folder for the runtime to use. The mounted location must match the --resources-path argument.
    depends_on:
      - app-reward
      - redis
    network_mode: "service:app-reward"
  redis:
    image: "redis:alpine"
    expose:
      - "6379"
volumes:
  rewarddata:
  testdata:
networks:
  default:
    name: dapr-network
    external: true